Needs["MagneticTB`"];

Clear[theta];
identity3 = IdentityMatrix[3];
continuousRotation = {
  {Cos[theta], -Sin[theta], 0},
  {Sin[theta], Cos[theta], 0},
  {0, 0, 1}
};
continuousInformation = <|
  "E" -> <|
    "space" -> {identity3, {0, 0, 0}},
    "spin" -> {identity3, 0}
  |>,
  "C_infty" -> <|
    "space" -> {identity3, {0, 0, 0}},
    "spin" -> {continuousRotation, 0},
    "continuous" -> theta
  |>
|>;
continuousSpinorMatrix = DiagonalMatrix[{
  Exp[-I theta/2],
  Exp[I theta/2]
}];

initfromrep[
  lattice -> {
    {a, 0, 0},
    {0, a, 0},
    {0, 0, a}
  },
  lattpar -> {a -> 1},
  wyckoffposition -> {{{0, 0, 0}, {0, 0, 0}}},
  symminformation -> continuousInformation,
  repinformation -> <|
    "Discrete" -> {{IdentityMatrix[2]}},
    "Continuous" -> <|
      "SiteMatrices" -> {{continuousSpinorMatrix}}
    |>
  |>,
  orbitalLabels -> {{"m=+1/2", "m=-1/2"}},
  InitialBondShells -> 2
];

simpleContinuousHamiltonian = symham[1];

slgName = "14.1.2.3.L.1";
slgData = documentationSpinLayer14123L1Fixture;
finiteRecords = slgData["FiniteRepresentatives"];
modelLattice = DiagonalMatrix[{1, 6/5, 4}];
seedPosition = {0, 0, 0};

finiteSymmetryInformation = AssociationThread[
  "g" <> ToString[#] & /@ Range[Length[finiteRecords]],
  Map[
    Function[record,
      <|
        "space" -> {
          record["SpaceMatrix"], record["Translation"]
        },
        "spin" -> {
          record["SpinMatrix"],
          Boole[TrueQ[record["AntiunitaryQ"]]]
        }
      |>
    ],
    finiteRecords
  ]
];
generatedSites = DeleteDuplicates[
  Mod[
    #["SpaceMatrix"].seedPosition + #["Translation"],
    1
  ] & /@ finiteRecords
];
siteStabilizerIndices = Select[
  Range[Length[finiteRecords]],
  Mod[
    finiteRecords[[#, "SpaceMatrix"]].seedPosition +
      finiteRecords[[#, "Translation"]],
    1
  ] === seedPosition &
];

(* These exact matrices were generated by the public
   SpinLayerCorepresentations API and frozen with the matching ordered
   operation records so this tutorial has no optional runtime dependency. *)
finiteSpinorMatrices = slgData["FiniteSpinorMatrices"];
siteSymmetryMatrices = (
  {{#[[1, 1]]}} & /@
    finiteSpinorMatrices[[siteStabilizerIndices]]
);

fullSymmetryInformation = Append[
  finiteSymmetryInformation,
  "C_infty" -> <|
    "space" -> {identity3, {0, 0, 0}},
    "spin" -> {continuousRotation, 0},
    "continuous" -> theta
  |>
];
continuousBandPath = {
  {{{0, 0, 0}, {1/2, 1/2, 0}}, {"G", "S"}},
  {{{1/2, 1/2, 0}, {1/2, 0, 0}}, {"S", "X"}},
  {{{1/2, 0, 0}, {0, 0, 0}}, {"X", "G"}}
};

ClearAll[initializeSLGDirectProduct];
initializeSLGDirectProduct[] := initfromrep[
  lattice -> modelLattice,
  lattpar -> {},
  wyckoffposition -> {{seedPosition, {0, 0, 1}}},
  symminformation -> fullSymmetryInformation,
  repinformation -> <|
    "Discrete" -> {finiteSpinorMatrices},
    "Continuous" -> <|
      "SiteMatrices" -> {
        ConstantArray[
          continuousSpinorMatrix,
          Length[generatedSites]
        ]
      }
    |>
  |>,
  orbitalLabels -> {{"m=+1/2", "m=-1/2"}},
  InitialBondShells -> 2,
  RepresentationMode -> "DirectProduct"
];

ClearAll[initializeSLGInduced];
initializeSLGInduced[] := initfromrep[
  lattice -> modelLattice,
  lattpar -> {},
  wyckoffposition -> {{seedPosition, {0, 0, 1}}},
  symminformation -> fullSymmetryInformation,
  repinformation -> <|
    "Discrete" -> {
      <|
        "ReferenceSiteIndex" -> 1,
        "SiteSymmetryOperationIndices" -> siteStabilizerIndices,
        "SiteSymmetryMatrices" -> siteSymmetryMatrices
      |>
    },
    "Continuous" -> <|
      "SiteMatrices" -> {{
        {{Exp[-I theta/2]}},
        {{Exp[I theta/2]}}
      }}
    |>
  |>,
  orbitalLabels -> {{"m=+1/2"}},
  InitialBondShells -> 5,
  RepresentationMode -> "Induced"
];
