(* ::Package:: *)

(* Forward declarations to prevent shadowing messages *)


BeginPackage["MagneticTB`"]


(* ::Subsubsection:: *)
(*core*)


(*set input data*)
init::usage = "init[opts] initializes a MagneticTB model from lattice, Wyckoff-position, symmetry, and basis-function data and prepares the requested bond shells."
initfromrep::usage = "initfromrep[opts] initializes a model from a complete closed finite group and complete program-generated representation data. It accepts no basisFunctions and performs no finite-group generation. An optional single pure-internal C_infty entry is removed before atom and bond compilation; its final per-site D(theta) matrices are supplied through repinformation and differentiated to one Hermitian generator."
unsymham ::usage = "unsymham[n] builds the unconstrained symbolic Hamiltonian for bond shell n from the current native model."
symham ::usage = "symham[n] constructs the symmetry-constrained Hamiltonian for bond shell n. Set \"Hermitian\"->False to keep reverse hoppings independent; the default is True."
basis::usage = "basis"
basisdict::usage = "basis"
kx ::usage = ""
ky ::usage = ""
kz ::usage = ""
a ::usage = ""
b ::usage = ""
c ::usage = ""
\[Alpha] ::usage = ""
\[Beta] ::usage = ""
\[Gamma] ::usage = ""
x ::usage = ""
y ::usage = ""
z ::usage = ""


(*output data*)
ops  ::usage ="ops"
braLatt ::usage = ""
gray ::usage = ""
grayrod::usage = ""
graylayer::usage = ""
typeI ::usage = ""
typeIII ::usage = ""
typeIV ::usage = ""
bnsdict ::usage = ""
ogdict ::usage = ""
ognumdict ::usage = ""
bondclassify  ::usage = ""
symminfo ::usage = ""
symmetryops  ::usage = ""
atompos ::usage=""
reclatt ::usage=""
latt ::usage=""
wcc ::usage = "Wannier center"
symmcompile ::usage = ""
lattice::usage = "Options for init"
wyckoffposition::usage = "Options for init"
symminformation::usage = "symminformation is an init option. The traditional list of {label,R,t,\"F\"|\"T\"} records remains the ordinary magnetic-group format. A discrete spin-space group uses the Association label-><|\"space\"->{R,t},\"spin\"->{S,0|1}|>. With GenerateSymmetryGroup->True either format supplies generators; with False it supplies the complete group. Only initfromrep additionally accepts one C_infty Association entry carrying \"continuous\"->theta; its space action must be exactly the identity and it is never included in the finite group, atom positions, or bond orbits."
basisFunctions::usage = "Options for init"
repinformation::usage = "repinformation is the required program-generated representation input for initfromrep. The legacy finite-only form is unchanged. With one internal C_infty use <|\"Discrete\"->oldFiniteData,\"Continuous\"-><|\"SiteMatrices\"->orbitBySiteDThetaMatrices|>|>; m is encoded by the supplied exact D(theta), and no basis-function inference is performed."
orbitalLabels::usage = "orbitalLabels supplies optional display-only local orbital labels for initfromrep; Automatic generates orb1, orb2, and so on from representation dimensions."
lattpar::usage = "Options for init"
debugQ::usage = "debugQ is a Boolean init and initfromrep compatibility option. It does not enable hidden fallback algorithms or change the physical model."
InitialBondShells::usage = "InitialBondShells is an init option specifying how many complete bond shells are prepared. symham only evaluates shells prepared by init; request a larger value and rerun init when more shells are needed."
GenerateSymmetryGroup::usage = "GenerateSymmetryGroup is an init option. False (default) uses the supplied records directly as the complete group without an input-stage closure check; True expands symminformation with the existing GenerateGroup function."
RepresentationMode::usage = "RepresentationMode is an init option with value \"DirectProduct\" or \"Induced\"."
CurrentModelSession::usage = "CurrentModelSession[] returns the current native in-memory model session created by init or initfromrep."
CompileMagneticTBInput::usage = "CompileMagneticTBInput[input] compiles ordinary magnetic-group list input or discrete spin-space-group dictionary input into a canonical model, verified representation data, and static directed-bond orbits without legacy globals. GenerateSymmetryGroup controls generator expansion."
brokenSymmetryInitRules::usage = "brokenSymmetryInitRules[generators] returns a complete list of init option rules for the subgroup generated by current symmetry-operation indices or labels. It closes the subgroup and splits current Wyckoff orbits without dropping atoms; use init@@rules explicitly to install the returned model. Use {} for the identity-only subgroup."
symmetrizationHRInit::usage = "symmetrizationHRInit[opts] returns native <|\"wcc\",\"DR\",\"symmetry\"|> data for HR symmetrization using the traditional string options."


(* ::Subsubsection:: *)
(*Plot*)


(*Plot*)
bandManipulate::usage = "bandManipulate[path,npoint,H] creates an interactive band plot for Hamiltonian H along path, with sliders for its symbolic parameters."
plotRange::usage = "plotRange is the public bandplot option that sets the displayed vertical energy range; its default is All."
yTicks::usage = "yTicks is a bandplot/showband option accepting Automatic, None, numeric tick positions, or standard tick specifications."

bandplot ::usage="bandplot[path,npoint,H,rules] plots numerical bands after applying parameter rules. path may be Automatic after init. Use plotRange, yTicks, FontSize, and FontFamily to control the display."
showband::usage = "showband[path,npoint,H,rules] is the presentation-oriented alias of bandplot. After init, showband[npoint,H,rules] automatically uses the conventional path of the current lattice."
banddata::usage = "banddata[path,npoint,H,rules,file] exports numerical band eigenvalues along path to file."
standardKPath::usage = "standardKPath[] returns a conventional high-symmetry path in reciprocal fractional coordinates for the current standardized lattice, including the 25 Brillouin-zone variations of the 14 three-dimensional Bravais lattices. Display labels follow the Bradley-Cracknell convention when available and otherwise retain the Setyawan-Curtarolo label."
showCrystalStructure::usage = "showCrystalStructure[] draws the current primitive cell and atoms; atoms carrying nonzero magnetic moments are marked by arrows."
showBrillouinZone::usage = "showBrillouinZone[] draws the first Brillouin zone and overlays the automatically selected conventional high-symmetry k path."
plotWilsonLoop::usage = "plotWilsonLoop[H,centers,occupied,start,end,parameterPath] plots Wilson-loop phase branches while translating the closed loop start->end along an explicit offset path or connected labeled path. Use \"PhaseConvention\"->\"WannierCenters\" for centers modulo one and \"Output\"->\"Data\" for sampled values."
plotSurfaceSpectrum::usage = "plotSurfaceSpectrum[data,path,{emin,emax}] plots the semi-infinite surface spectral weight -Im Tr[Gsurface]/Pi along a two-dimensional surface-momentum path using the hopping-based surface Green function. Use \"Output\"->\"Data\" for the sampled energy-momentum grid."
plotBerryCurvature2D::usage = "plotBerryCurvature2D[H,centers,occupied,{{u1,u2},{v1,v2}}] samples the existing Wilson-plaquette berryCurvature on an oriented momentum plane and returns a signed density plot. Directions selects the two coordinates, FixedCoordinates selects the slice, and Output->\"Data\" returns the sampled curvature grid."
plotBerryCurvature3D::usage = "plotBerryCurvature3D[H,centers,occupied,{{k1min,k1max},{k2min,k2max},{k3min,k3max}}] plots the Berry-curvature vector field with components {F23,F31,F12}. Arrow direction shows orientation, while length and color show magnitude; Output->\"Data\" returns the complete vector grid."
plotRealSpaceWavefunction::usage = "plotRealSpaceWavefunction[data,state] maps a finite-system wavefunction onto the BasisRecords returned by buildRealSpaceHamiltonian[...,\"Output\"->\"Data\"]. Orbitals at the same atomic position are combined by default; sphere volume represents probability and PhaseColoring optionally displays the representative complex phase."
showSymmetryRepresentations::usage = "showSymmetryRepresentations[] displays the cached full representation matrices for the symmetry generators. Use All, one operation index, or a list of indices to select other prepared operations."
orbitalTable::usage = "orbitalTable[] returns a Grid displaying the fixed Hamiltonian orbital numbering prepared by init, including Wyckoff orbit, equivalent atom, fractional and Cartesian positions, input and actual basis states, and extensible spin-state metadata. It never evaluates symham or mutates the model session."
showHamiltonianBasis::usage = "showHamiltonianBasis[] displays the Hamiltonian basis order prepared by init or initfromrep, including site, Wyckoff orbit, equivalent atom, position, and local orbital. Function-basis induced mode shows the transformed basis state; explicit-representation induced mode shows abstract orbital labels with transport provenance. showHamiltonianBasis[i,j] identifies the row (bra) and column (ket) basis states of H[[i,j]]."
showHoppingParameters::usage = "showHoppingParameters[n] displays the representative real-space hopping matrix elements from which each independent parameter of cached symham[n] originates. showHoppingParameters[n,p] displays every symmetry-propagated real-space occurrence of parameter p. It never evaluates symham implicitly."


(*Functions*)
pointMatrix  ::usage = "pointMatrix[operations,basis,lattice] compiles exact unitary point-operation matrices with the traditional input form."
tokpathvasp ::usage = ""


realham2d ::usage=""



(* ::Subsubsection:: *)
(*IO*)


(*
Interface
*)
hop::usage = "hop[n,rules] exports cached real-space hopping matrices for shells 1 through n in wannier90_hr.dat format, while hop[{n1,n2,...},rules] exports selected solved shells. hop[ham,rules] remains available as a separate converter for hand-written exponential H(k); \"wcc\" defaults to Automatic, which uses centers from the current model session when available and otherwise uses zero centers."
readHR::usage = "readHR[file] strictly reads a complete wannier90_hr.dat file and returns structured real-space H(R) data. Set \"ncell\"->n only when an explicit cell cutoff is desired."


(* ::Subsubsection:: *)
(*Real-space hopping and surfaces*)


hoppingData::usage = "hoppingData[n,rules] returns numeric real-space hopping blocks H(R) for cached symham shells 1 through n; hoppingData[{n1,n2,...},rules] selects explicit cached shells. It reads the real-space shell cache directly and never reconstructs hopping from H(k)."
transformHoppings::usage = "transformHoppings[data,T] transforms hopping blocks H(R) to the cell whose direct-lattice row vectors are T times the old lattice. T must be a nonsingular 3 by 3 integer matrix; exact Smith decomposition determines all cell representatives without a spatial cutoff."
buildBlochHamiltonian::usage = "buildBlochHamiltonian[data,{k1,k2,k3}] constructs the fully three-dimensionally periodic Bloch Hamiltonian directly from hopping blocks H(R). CellMatrix->T first creates the exact integer supercell, so the returned matrix has Abs[Det[T]] times the original orbital dimension and k is expressed in the supercell reciprocal fractional basis."
buildRealSpaceHamiltonian::usage = "buildRealSpaceHamiltonian[data,{n1,n2,n3}] builds a sparse rectangular finite Hamiltonian from hopping blocks H(R). The second argument may instead be any nonempty duplicate-free list of integer cell coordinates, producing an arbitrary open-boundary shape. Output->\"Data\" includes matrix-aligned BasisRecords for real-space plotting."
buildSlabHamiltonian::usage = "buildSlabHamiltonian[data,{n1,n2,n3},k] builds a hopping-based hybrid-space Hamiltonian with continuous crystal momentum k along PeriodicDirections and finite open cells along the remaining directions. The default PeriodicDirections->{1,2} gives a slab normal to axis 3; one periodic direction gives a ribbon or rod."
surfaceGreenFunction::usage = "surfaceGreenFunction[data,{k1,k2},energy] computes the retarded semi-infinite surface Green function directly from hopping blocks H(R) using principal-layer decimation. The first two cell axes span the surface and the third is the stacking direction; CellMatrix may transform the cell first."
surfaceSpectralFunction::usage = "surfaceSpectralFunction[data,{k1,k2},energy] returns -Im Tr[Gsurface]/Pi from the hopping-based semi-infinite surface Green function."
pointChernNumber::usage = "pointChernNumber[H,occupied,k0,r] computes the integer Chern charge enclosed by an oriented cube of radius r around the three-dimensional momentum point k0. H may be a numeric-momentum function H[k] or a matrix using kx, ky, kz; the occupied subspace must remain gapped on the enclosing surface."
findGaplessPoints::usage = "findGaplessPoints[H,occupied] searches the periodic Brillouin zone for zeros of the direct gap between bands occupied and occupied+1 using a periodic eigenvalue-only grid followed by bounded local minimization of gap^2. CandidateCount caps the total refinement seeds; RefinementMethod selects \"PrincipalAxis\" (default) or \"QuasiNewton\". H may be a numeric-momentum function or a matrix using kx, ky, kz; use Output->\"Data\" for search diagnostics."


(* ::Subsubsection:: *)
(*Wilson*)


(*Wilson loop (testing)*)
wLoop ::usage = "init"
berryph ::usage = ""
z2path ::usage =""
wilsonLoop ::usage = "wilsonLoop[h,wcc,occ,start,end] computes the tight-binding Wilson-loop phases (in units of Pi) for an isolated occupied subspace along the forward reciprocal-lattice loop start to end. The implementation uses SVD-unitarized occupied-subspace links and the orbital-center sewing matrix. Use \"Output\"->\"WannierCenters\", \"Eigenvalues\", or \"Data\" for alternate results and diagnostics."
berryPhase::usage = "berryPhase[h,wcc,occ,path] computes the gauge-invariant total Berry phase in radians for an isolated occupied subspace along an explicitly sampled closed momentum path. The endpoint may differ from the start by a reciprocal-lattice vector; orbital-center sewing and SVD-unitarized links follow wilsonLoop conventions."
berryCurvature::usage = "berryCurvature[h,wcc,occ,k] computes the total occupied-subspace Berry curvature at k from the oriented Berry flux through a small Wilson plaquette. Directions selects the coordinate plane, StepSize controls the plaquette, and Output->\"Data\" returns diagnostics."
(* ::Subsubsection:: *)
(*Corep*)


getMSGElemFromMSGCorep::usage = ""
getTBBandCorep::usage = ""


(* ::Subsubsection:: *)
(*Utilities*)


symhamII::usage = "symhamII[H] rewrites a Bloch Hamiltonian from convention I to convention II. The string option \"wcc\" supplies explicit orbital centers; its default None uses centers prepared by init."
showbonds ::usage = "showbonds[n] displays the cached bond length and directed bonds for the (n-1)-th neighbour shell prepared by init. It never extends the bond search."
GenerateGroup::usage = "GenerateGroup[generators,identity,multiply] generates a finite group with the supplied multiplication function. SameTest selects the group-element equality predicate and defaults to SameQ."
getGenerator::usage = "getGenerator[group,identity,multiply] is a deprecated compatibility wrapper that greedily finds generators using the canonical abstract-group module. SameTest defaults to SameQ."
showMSGWyckoff::usage = "showMSGWyckoff[group] displays the complete magnetic Wyckoff table for a database group."


msgop::usage = "msgop[group] returns the magnetic-space-group operations for a magnetic group specified by a MagneticTB database identifier such as gray[n], typeI[n], typeIII[n], or typeIV[n]."
mlgop::usage = "mlgop[group] returns ordered magnetic layer-group operations from the bundled database."
mrgop::usage = "mrgop[group] returns ordered magnetic rod-group operations from the bundled database."
texOutput ::usage =""


(* ::Subsubsection:: *)
(*Fitting*)


bandManipulateEig::usage = "bandManipulateEig[H,referenceBands] opens an interactive overlay of the eigenvalues of H and numeric reference bands such as the output of vaspEig."
fittingTB::usage = "fittingTB[H,eigenvalueData,kRange,initialRules] fits an affine-linear tight-binding Hamiltonian by minimizing selected TB-reference band residuals with a finite-difference Levenberg-Marquardt algorithm. kRange retains its legacy meaning as 1-based record indices. EnergyWindow selects reference energies inclusively; KPointNeighborhood selects a periodic minimum-image radius or component range around a fractional reciprocal coordinate; BandSelection selects 1-based reference positions; and ResidualWeights supplies a nonnegative record-by-band weight matrix. Selectors are intersected. Sorted model eigenvalue j is paired with reference position j. The result reports UsedKPointCount, UsedKPointIndices, ResidualCount, the effective band selection, convergence diagnostics, objective values, and a ComparisonPlot. The default options preserve the legacy all-record/all-band behavior."
vaspEig::usage = "vaspEig[file,efermi,spin,startBand,endBand] reads selected bands from a VASP EIGENVAL file and returns {{kx,ky,kz},{energy1,...}} records shifted by efermi."
compareBand::usage = "compareBand[path,npoint,H,rules,referenceBands] overlays tight-binding bands from H with supplied reference eigenvalues. plotRange controls the displayed energy interval."
EndPackage[]
