use std::fmt::Display;

use crate::GroupError;

fn contains_by<T, S>(values: &[T], value: &T, same: &mut S) -> bool
where
    S: FnMut(&T, &T) -> bool,
{
    values.iter().any(|candidate| same(candidate, value))
}

fn unique_by<T: Clone, S>(values: impl IntoIterator<Item = T>, same: &mut S) -> Vec<T>
where
    S: FnMut(&T, &T) -> bool,
{
    values.into_iter().fold(Vec::new(), |mut result, value| {
        if !contains_by(&result, &value, same) {
            result.push(value);
        }
        result
    })
}

/// Enumerates the exact finite closure of opaque generators in the same stable
/// layer order as Mathematica `GroupEnumeration::GenerateGroup`.
///
/// # Errors
///
/// Returns an explicit error if multiplication fails or a generator does not
/// return to the identity within the frozen 200-product boundary.
pub fn generate_group<T, F, E>(
    generators: &[T],
    identity: &T,
    multiply: F,
) -> Result<Vec<T>, GroupError>
where
    T: Clone + PartialEq,
    F: FnMut(&T, &T) -> Result<T, E>,
    E: Display,
{
    generate_group_by(generators, identity, multiply, |left, right| left == right)
}

/// Enumerates an exact finite closure using a caller-provided equivalence
/// relation, matching Mathematica's `SameTest` option.
///
/// # Errors
///
/// Returns an explicit error if multiplication fails or a generator does not
/// return to the identity within the frozen 200-product boundary.
pub fn generate_group_by<T, F, S, E>(
    generators: &[T],
    identity: &T,
    mut multiply: F,
    mut same: S,
) -> Result<Vec<T>, GroupError>
where
    T: Clone,
    F: FnMut(&T, &T) -> Result<T, E>,
    S: FnMut(&T, &T) -> bool,
    E: Display,
{
    if generators.is_empty() {
        return Ok(vec![identity.clone()]);
    }
    let mut cyclic_subgroups = Vec::with_capacity(generators.len());
    for generator in generators {
        let mut cyclic = Vec::new();
        let mut product = generator.clone();
        for _ in 0..200 {
            cyclic.push(product.clone());
            if same(&product, identity) {
                break;
            }
            product = multiply(&product, generator).map_err(|error| {
                GroupError::new(
                    "generator_product_failed",
                    "generate_group",
                    error.to_string(),
                )
            })?;
        }
        if cyclic.last().is_none_or(|value| !same(value, identity)) {
            return Err(GroupError::new(
                "generator_order_exceeds_limit",
                "generate_group",
                "a generator did not return to the identity within 200 products",
            ));
        }
        cyclic_subgroups.extend(cyclic);
    }
    let first_layer = unique_by(cyclic_subgroups, &mut same);
    let mut next_layer = Vec::new();
    for left in &first_layer {
        for right in &first_layer {
            next_layer.push(multiply(left, right).map_err(|error| {
                GroupError::new(
                    "closure_product_failed",
                    "generate_group",
                    error.to_string(),
                )
            })?);
        }
    }
    next_layer = unique_by(next_layer, &mut same);
    let mut new_elements = next_layer
        .iter()
        .filter(|element| !contains_by(&first_layer, element, &mut same))
        .cloned()
        .collect::<Vec<_>>();
    let mut first_layer = next_layer.clone();
    while !new_elements.is_empty() {
        let mut products = Vec::new();
        for left in &new_elements {
            for right in &first_layer {
                products.push(multiply(left, right).map_err(|error| {
                    GroupError::new(
                        "closure_product_failed",
                        "generate_group",
                        error.to_string(),
                    )
                })?);
            }
        }
        next_layer = unique_by(products, &mut same);
        new_elements = next_layer
            .iter()
            .filter(|element| !contains_by(&first_layer, element, &mut same))
            .cloned()
            .collect();
        first_layer.clone_from(&next_layer);
    }
    next_layer.sort_by_key(|element| !same(element, identity));
    Ok(next_layer)
}

/// Greedily chooses concrete generators from a complete ordered element list.
///
/// # Errors
///
/// Returns an explicit error if multiplication fails or the supplied elements
/// do not form the exact closure generated by the selected elements.
pub fn find_concrete_generators<T, F, E>(
    elements: &[T],
    identity: &T,
    multiply: F,
) -> Result<Vec<T>, GroupError>
where
    T: Clone + PartialEq,
    F: FnMut(&T, &T) -> Result<T, E>,
    E: Display,
{
    find_concrete_generators_by(elements, identity, multiply, |left, right| left == right)
}

/// Greedily chooses concrete generators using a caller-provided equivalence
/// relation, matching Mathematica `getGenerator` with its `SameTest` option.
///
/// # Errors
///
/// Returns an explicit error if multiplication fails or the supplied elements
/// do not form the exact closure generated by the selected elements.
pub fn find_concrete_generators_by<T, F, S, E>(
    elements: &[T],
    identity: &T,
    mut multiply: F,
    mut same: S,
) -> Result<Vec<T>, GroupError>
where
    T: Clone,
    F: FnMut(&T, &T) -> Result<T, E>,
    S: FnMut(&T, &T) -> bool,
    E: Display,
{
    if elements.is_empty() || !contains_by(elements, identity, &mut same) {
        return Err(GroupError::new(
            "invalid_element_list",
            "find_concrete_generators",
            "complete elements must contain the identity",
        ));
    }
    if elements.len() == 1 {
        return Ok(vec![identity.clone()]);
    }
    let mut generators = Vec::new();
    let mut generated = vec![identity.clone()];
    for candidate in elements {
        if contains_by(&generated, candidate, &mut same) {
            continue;
        }
        let mut trial = generators.clone();
        trial.push(candidate.clone());
        let candidate_generated = generate_group_by(&trial, identity, &mut multiply, &mut same)?;
        if candidate_generated.len() > generated.len() {
            generators.push(candidate.clone());
            generated = candidate_generated;
        }
        if elements.len() == generated.len()
            && elements
                .iter()
                .all(|element| contains_by(&generated, element, &mut same))
        {
            return Ok(generators);
        }
    }
    Err(GroupError::new(
        "incomplete_generation",
        "find_concrete_generators",
        "the supplied exact multiplication did not regenerate every element",
    ))
}

#[cfg(test)]
mod tests {
    use super::{find_concrete_generators, generate_group};

    #[test]
    fn c4_generation_is_identity_first_and_deterministic() {
        let multiply =
            |left: &u8, right: &u8| -> Result<u8, &'static str> { Ok((left + right) % 4) };
        let group = generate_group(&[1], &0, multiply).expect("C4");
        assert_eq!(group, [0, 2, 3, 1]);
        let generators = find_concrete_generators(&group, &0, multiply).expect("generators");
        assert_eq!(generators, [2, 3]);
    }
}
