"""Compatibility facade for the domain-structured Rust-backed modeling API.

New code may import from the domain modules directly.  Existing
``magnetictb.modeling`` imports remain stable through these explicit re-exports.
"""

from .linear_algebra import (
    CyclotomicElement,
    ExactAtom,
    ExactExpr,
    ExactField,
    ExactMatrix,
    MatrixInput,
    PhaseCoordinate,
    QuadraticNumber,
    _call,
    _coerce_expr,
    _cyclotomic_to_user,
    _decode_element,
    _decode_input_exact,
    _decode_lattice_parameters,
    _decode_matrix,
    _decode_nested_elements,
    _decode_phase_coordinate,
    _decode_quadratic,
    _encode_cyclotomic_element,
    _encode_evaluation_scalar,
    _encode_exact,
    _encode_lattpar,
    _encode_phase_coordinate,
    _encode_tree,
    _field_from_context,
    _format_exact_payload,
    _freeze_json,
    _freeze_matrix_input,
    _hashable_json,
    _matrix,
    _matrix_to_user,
    _ordered,
    _phase_coordinate_to_user,
    _quadratic_to_user,
    _root_of_unity_text,
    _strict_bool,
    _tagged_list,
    _thaw_json,
    cos,
    exact_complex,
    exp,
    root_of_unity,
    sin,
    sqrt,
    symbol,
)

from .symmetry import (
    SpinSpaceOperation,
    SymmetryOperation,
    _decode_broken_symmetry_operations,
    _decode_prepared_symmetry_operations,
    _encode_symmetry,
)

from .data import (
    MSG,
    MagneticGroupSelector,
    Wyckoff,
    _MagneticGroupDictionary,
    _SubperiodicGrayDictionary,
    _catalog_exact_to_user,
    _catalog_matrix_to_user,
    _data_catalog,
    _normalise_data_wyckoff,
    _normalise_wyckoff,
    _stable_record_scalar,
    _subperiodic_operations,
    bnsdict,
    gray,
    graylayer,
    grayrod,
    mlgop,
    mrgop,
    msgop,
    ogdict,
    ognumdict,
    typeI,
    typeIII,
    typeIV,
)

from .representation_theory import (
    DirectProductRepresentation,
    ExplicitPolynomialBasis,
    InducedOrbit,
    InducedRepresentation,
    _basis_display_labels,
    _encode_basis_functions,
    _encode_representation_information,
    _normalise_basis,
    _normalise_orbital_labels,
    _reject_inexact_polynomial_value,
)

from .tight_binding import (
    BondRecord,
    Hamiltonian,
    HamiltonianBasisTerm,
    HamiltonianExpression,
    HamiltonianMatrixContribution,
    HamiltonianParameter,
    HamiltonianSpace,
    HamiltonianTerm,
    OrbitalRecord,
    _bond_to_user,
    _decode_bond,
    _decode_hamiltonian,
    _encode_symbolic_matrix_entries,
    _format_cyclotomic,
    _format_phase_coordinate,
    _format_quadratic,
    _parameter_name,
    _phase_coordinate_is_zero,
)

from .physical_representation import (
    pointMatrix,
)

from .model import (
    CompileMagneticTBInput,
    CurrentModelSession,
    PreparedModel,
    _CURRENT_MODEL,
    _CompilationRecipe,
    _base_compiler_input,
    _broken_symmetry_rules_for_model,
    _clear_current_model_for_tests,
    _compile_all_shells,
    _compile_data_prepared_model,
    _decode_broken_symmetry_basis,
    _prepare_data_model,
    _prepare_explicit_model,
    _print_generators,
    _stable_default_lattice,
    _stable_default_lattpar,
    _stable_default_symmetry,
    _stable_default_wyckoff,
    _stable_keyword_alias,
    _symham_ii_for_model,
    brokenSymmetryInitRules,
    compile_magnetic_tb_input,
    current_model,
    hamiltonian_object,
    hamiltonian_space,
    init,
    initfromrep,
    prepare_model,
    prepare_model_from_rep,
    symham,
    symhamII,
    unsymham,
)
