"""Stable 2.0.10 presentation utilities; no mathematical algorithms live here."""

from __future__ import annotations

import re
from collections.abc import Sequence
from fractions import Fraction
from typing import Any

from .linear_algebra import _root_of_unity_text
from .tight_binding import Hamiltonian, HamiltonianExpression


def _root_exponential_tex(source: str) -> str:
    match = re.fullmatch(r"(-?)(?:(\d+)\*)?pi\*i(?:/(\d+))?", source)
    if match is None:
        return rf"e^{{{source}}}"
    sign, magnitude, denominator = match.groups()
    coefficient = "" if magnitude in (None, "1") else magnitude
    numerator = rf"{sign}{coefficient}\pi i"
    exponent = rf"\frac{{{numerator}}}{{{denominator}}}" if denominator else numerator
    return rf"e^{{{exponent}}}"


def _balanced_exponentials(source: str) -> str:
    marker = "exp(I*("
    cursor = 0
    output: list[str] = []
    while True:
        start = source.find(marker, cursor)
        if start < 0:
            output.append(source[cursor:])
            return "".join(output)
        output.append(source[cursor:start])
        depth = 1
        end = start + len(marker)
        while end < len(source) and depth:
            if source[end] == "(":
                depth += 1
            elif source[end] == ")":
                depth -= 1
            end += 1
        if depth:
            output.append(source[start:])
            return "".join(output)
        phase = source[start + len(marker) : end - 1]
        if end < len(source) and source[end] == ")":
            end += 1
        output.append(r"e^{i\left(" + phase + r"\right)}")
        cursor = end


def _scalar_tex(value: Any) -> str:
    if isinstance(value, Fraction):
        if value.denominator == 1:
            return str(value.numerator)
        return rf"\frac{{{value.numerator}}}{{{value.denominator}}}"
    source = str(value).replace("+ -", "- ")
    source = re.sub(
        r"root_of_unity\((\d+),\s*(-?\d+)\)",
        lambda match: _root_of_unity_text(int(match.group(1)), int(match.group(2))),
        source,
    )
    source = re.sub(r"e\^\(([^()]*)\)", lambda match: _root_exponential_tex(match.group(1)), source)
    source = _balanced_exponentials(source)
    source = re.sub(r"\b(kx|ky|kz)\b", lambda match: rf"k_{{{match.group(0)[1]}}}", source)
    source = re.sub(
        r"\b([A-Za-z]+)(\d+)\b",
        lambda match: rf"{match.group(1)}_{{{match.group(2)}}}",
        source,
    )
    source = re.sub(r"sqrt\((\d+)\)", lambda match: rf"\sqrt{{{match.group(1)}}}", source)
    source = re.sub(
        r"(?<![\w}])(-?\d+)/(\d+)",
        lambda match: rf"\frac{{{match.group(1)}}}{{{match.group(2)}}}",
        source,
    )
    return source.replace("I", "i").replace("*", r"\,")


def texOutput(matrix: Any) -> str:
    """Return the stable-style TeX string for a scalar or matrix result.

    Formatting is a Python presentation concern.  Any Hamiltonian expression
    supplied here must already have been generated by the Rust core.
    """

    if isinstance(matrix, Hamiltonian):
        matrix = matrix.matrix
    if isinstance(matrix, HamiltonianExpression):
        return _scalar_tex(matrix)
    if (
        isinstance(matrix, Sequence)
        and not isinstance(matrix, (str, bytes))
        and matrix
        and all(isinstance(row, Sequence) and not isinstance(row, (str, bytes)) for row in matrix)
    ):
        rows = tuple(tuple(row) for row in matrix)
        columns = len(rows[0])
        if columns == 0 or any(len(row) != columns for row in rows):
            raise ValueError("texOutput matrix rows must have equal nonzero length")
        body = r" \\ ".join(" & ".join(_scalar_tex(value) for value in row) for row in rows)
        return r"\begin{pmatrix}" + body + r"\end{pmatrix}"
    return _scalar_tex(matrix)


tex_output = texOutput
