"""Verified ordinary ``init`` examples for the Web model workflow."""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional


def _data_init_example(
    *,
    example_id: str,
    title: str,
    crystal_system: str,
    description: str,
    source_case: str,
    space_group_number: int,
    msg_id: str,
    lattice_parameters: Dict[str, Any],
    letter: str,
    source_ordinal: int,
    coordinate_parameters: Dict[str, Any],
    moment_parameters: Dict[str, Any],
    basis_functions: List[str],
    initial_bond_shells: int = 2,
    representation_mode: Literal["DirectProduct", "Induced"] = "DirectProduct",
    band_parameters: Optional[Dict[str, float]] = None,
    band_parameter_source: Optional[str] = None,
) -> Dict[str, Any]:
    """Build one ordinary init request from an already replayed model case."""

    result = {
        "id": example_id,
        "title": title,
        "crystal_system": crystal_system,
        "description": description,
        "source_case": source_case,
        "space_group_number": space_group_number,
        "band_shells": list(range(1, initial_bond_shells + 1)),
        "band_parameters": dict(band_parameters or {}),
        "band_parameter_source": band_parameter_source,
        "request": {
            "label": title,
            "lattice": {
                "preset": "msg_bravais",
                "parameters": lattice_parameters,
            },
            "symmetry": {"source": "msg", "msg_id": msg_id, "operations": []},
            "orbits": [
                {
                    "letter": letter,
                    "source_ordinal": source_ordinal,
                    "coordinate_parameters": coordinate_parameters,
                    "moment_parameters": moment_parameters,
                    "basis_functions": basis_functions,
                }
            ],
            "initial_bond_shells": initial_bond_shells,
            "generate_symmetry_group": False,
            "representation_mode": representation_mode,
            "exact_field": {"preset": "crystallographic"},
        },
    }
    return result


def _explicit_init_example(
    *,
    example_id: str,
    title: str,
    description: str,
    source_case: str,
    operations: List[Dict[str, Any]],
    moment: List[Any],
    initial_bond_shells: int = 2,
    generate_symmetry_group: bool = False,
    direct_representation: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Build one runnable explicit spin-space-group example."""

    return {
        "id": example_id,
        "title": title,
        "crystal_system": "Spin group",
        "description": description,
        "source_case": source_case,
        "space_group_number": None,
        "band_shells": list(range(1, initial_bond_shells + 1)),
        "band_parameters": {},
        "band_parameter_source": None,
        "request": {
            "label": title,
            "lattice": {"preset": "simple_cubic", "parameters": {}},
            "symmetry": {"source": "explicit", "msg_id": None, "operations": operations},
            "orbits": [
                {
                    "letter": "site",
                    "source_ordinal": None,
                    "position": [0, 0, 0],
                    "moment": moment,
                    "basis_functions": ["sup", "sdn"],
                }
            ],
            "initial_bond_shells": initial_bond_shells,
            "generate_symmetry_group": generate_symmetry_group,
            "representation_mode": "DirectProduct",
            "exact_field": {"preset": "crystallographic"},
            "direct_representation": direct_representation,
        },
    }


INIT_EXAMPLES: tuple[Dict[str, Any], ...] = (
    _data_init_example(
        example_id="graphene-pz",
        title="Graphene Pz",
        crystal_system="Hexagonal",
        description="gray(191) / 2c / pz，稳定帮助例的三键层石墨烯模型。",
        source_case="model.graphene_pz.json + stable help init",
        space_group_number=191,
        msg_id="msg-1464",
        lattice_parameters={"a": "1", "c": "3"},
        letter="c",
        source_ordinal=2,
        coordinate_parameters={},
        moment_parameters={},
        basis_functions=["pz"],
        initial_bond_shells=3,
        band_parameters={"e1": 0.05, "t1": 0.5, "r1": 0.02},
        band_parameter_source="stable 2.0.10 bandManipulate help example",
    ),
    _data_init_example(
        example_id="mos2-three-band",
        title="MoS₂ 三带 d 模型",
        crystal_system="Hexagonal",
        description="Mo 位点 dz2 / dxy / dx2-y2，onsite 与最近邻共八个参数。",
        source_case="stable help three-band MoS2",
        space_group_number=187,
        msg_id="msg-1440",
        lattice_parameters={"a": "1", "c": "4"},
        letter="a",
        source_ordinal=1,
        coordinate_parameters={},
        moment_parameters={},
        basis_functions=["dz2", "dxy", "dx2-y2"],
        band_parameters={
            "e1": 1.046,
            "e2": 2.104,
            "t1": -0.184,
            "t2": 0.401,
            "t3": 0.218,
            "t4": 0.507,
            "t5": 0.338,
            "t6": 0.057,
        },
        band_parameter_source="stable 2.0.10 GeneralExamples MoS2 bandplot",
    ),
    _data_init_example(
        example_id="triclinic-type-iv-s",
        title="三斜 Type-IV s",
        crystal_system="Triclinic",
        description="稳定 TRI1a 三斜 metric、一般 Wyckoff 位置与三分量磁矩。",
        source_case="model.data_triclinic_1.3_a.json + stable TRI1a path catalogue",
        space_group_number=1,
        msg_id="msg-0003",
        lattice_parameters={
            "a": "1", "b": "6/5", "c": "7/5",
            "α": "Pi/3", "β": "Pi/3", "γ": "Pi/3",
        },
        letter="a",
        source_ordinal=2,
        coordinate_parameters={"x": "1/7", "y": "2/11", "z": "3/13"},
        moment_parameters={"mx": "1/5", "my": "2/7", "mz": "3/11"},
        basis_functions=["s"],
    ),
    _data_init_example(
        example_id="monoclinic-type-iii-s",
        title="单斜 Type-III s",
        crystal_system="Monoclinic",
        description="非正交单斜晶格、一般位置与磁矩约束。",
        source_case="model.data_monoclinic_3.3_e.json",
        space_group_number=3,
        msg_id="msg-0010",
        lattice_parameters={"a": "1", "b": "6/5", "c": "7/5", "β": "Pi/3"},
        letter="e",
        source_ordinal=2,
        coordinate_parameters={"x": "1/7", "y": "2/11", "z": "3/13"},
        moment_parameters={"mx": "1/5", "my": "2/7", "mz": "3/11"},
        basis_functions=["s"],
    ),
    _data_init_example(
        example_id="tetragonal-type-iii-s",
        title="四方 Type-III s",
        crystal_system="Tetragonal",
        description="四方晶格、特殊平面位置与轴向磁矩。",
        source_case="model.data_tetragonal_75.3_c.json",
        space_group_number=75,
        msg_id="msg-0663",
        lattice_parameters={"a": "1", "c": "3/2"},
        letter="c",
        source_ordinal=2,
        coordinate_parameters={"z": "3/13"},
        moment_parameters={"mz": "3/11"},
        basis_functions=["s"],
    ),
    _explicit_init_example(
        example_id="noncollinear-octahedral-spin-group",
        title="非共线八面体自旋群",
        description="稳定帮助例的 C4z 与 C3xyz 自旋生成元，闭包为 24 个有序操作。",
        source_case="stable 2.0.10 ValidatedModels noncollinearSSG",
        operations=[
            {
                "kind": "spin_space",
                "label": "C4zspin",
                "rotation": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
                "translation": [0, 0, 0],
                "spin_rotation": [[0, -1, 0], [1, 0, 0], [0, 0, 1]],
                "antiunitary": False,
                "continuous_parameter": None,
            },
            {
                "kind": "spin_space",
                "label": "C3xyzspin",
                "rotation": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
                "translation": [0, 0, 0],
                "spin_rotation": [[0, 0, 1], [1, 0, 0], [0, 1, 0]],
                "antiunitary": False,
                "continuous_parameter": None,
            },
        ],
        moment=[0, 0, 0],
        generate_symmetry_group=True,
    ),
    _data_init_example(
        example_id="cubic-p-direct",
        title="立方 px/py/pz 直积",
        crystal_system="Cubic",
        description="gray(221) / 3d；显式局域 px、py、pz 的 DirectProduct。",
        source_case="stable 2.0.10 GettingStarted cubicPDirect",
        space_group_number=221,
        msg_id="msg-1595",
        lattice_parameters={"a": "1"},
        letter="d",
        source_ordinal=3,
        coordinate_parameters={},
        moment_parameters={},
        basis_functions=["px", "py", "pz"],
        initial_bond_shells=1,
    ),
    _data_init_example(
        example_id="cubic-px-induced",
        title="立方 px 诱导",
        crystal_system="Cubic",
        description="gray(221) / 3d；从参考点 px 的稳定子群表示诱导完整轨道。",
        source_case="stable 2.0.10 GettingStarted cubicPInduced",
        space_group_number=221,
        msg_id="msg-1595",
        lattice_parameters={"a": "1"},
        letter="d",
        source_ordinal=3,
        coordinate_parameters={},
        moment_parameters={},
        basis_functions=["px"],
        initial_bond_shells=1,
        representation_mode="Induced",
    ),
    _data_init_example(
        example_id="magnetic-kagome",
        title="磁性 Kagome",
        crystal_system="Hexagonal",
        description="BNS 191.238 / 3f；原胞三站点与 120° 面内磁矩。",
        source_case="stable 2.0.10 MSG/Wyckoff Data 191.238-3f",
        space_group_number=191,
        msg_id="msg-1468",
        lattice_parameters={"a": "1", "c": "3"},
        letter="f",
        source_ordinal=3,
        coordinate_parameters={},
        moment_parameters={"mx": "1"},
        basis_functions=["s"],
    ),
)
